version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
# Uncomment while init
    volumes:
       - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - app_network

volumes:
  mysql_data:

networks:
  app_network:
